[workspace]

members = [
    "h3ron-h3-sys",
    "h3ron",
    "h3ron-ndarray",
    "h3ron-graph",
    "h3ron-playground",
]
[profile.release]
debug = true # for flamegraph
lto = false # for callgrind

#debug = false
#lto = "fat"

[profile.bench]
debug = true
