name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "14 4 * * 1"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Pull submodules
      run: git submodule init && git submodule update
    - name: Install system dependencies
      # https://github.com/actions/virtual-environments/issues/2924
      run: sudo apt-get update && sudo apt-get install cmake libgdal-dev
    - name: Build
      run: cargo build --verbose
    - name: Run rust tests
      # run only selected packages while https://github.com/PyO3/pyo3/issues/340 is open
      run: cargo test -p h3ron && cargo test -p h3ron-ndarray
    - name: install h3ronpy python dependencies
      working-directory: h3ronpy
      run: python install-dev-dependencies.py
    - name: build h3ronpy
      working-directory: h3ronpy
      run: maturin develop
    - name: run python tests
      working-directory: h3ronpy
      run: pytest -v
