name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "14 4 * * 1"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull submodules
      run: git submodule init && git submodule update
    - name: Install system dependencies
      # https://github.com/actions/virtual-environments/issues/2924
      run: sudo apt-get update && sudo apt-get install cmake libgdal-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      # run only selected packages while https://github.com/PyO3/pyo3/issues/340 is open
      run: cargo test -p h3ron && cargo test -p h3ron-ndarray
    # todo: add benchmarks?
